import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
# Disclaimer: Code generated by Gemini, revised by student

# Setup configurations
configs = [
    {"name": "Stable Focus", "A": 1.0, "B": 1.0},
    {"name": "Limit Cycle Oscillations", "A": 1.0, "B": 3.0}
]


def objective(t, z, A, B):
    x, y = z
    x_hat = A + x**2*y - B*x - x
    y_hat = B*x - x**2 * y
    return [x_hat, y_hat]

# Time span for simulation
t_span = (0, 15)
t_eval = np.linspace(t_span[0], t_span[1], 500)

# Two different initial conditions to test for each case
init_conds = [[0.5, 0.5], [2.0, 4.0]]


# Plotting
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for i, config in enumerate(configs):
    A, B = config["A"], config["B"]
    
    ax_time = axes[i, 0]
    ax_phase = axes[i, 1]
    
    for idx, ic in enumerate(init_conds):
        sol = solve_ivp(objective, t_span, ic, args=(A, B), t_eval=t_eval)
        
        # Plot Time Course (solid for x, dashed for y)
        ax_time.plot(sol.t, sol.y[0], label=f'x (IC: {ic})', linestyle='-')
        ax_time.plot(sol.t, sol.y[1], label=f'y (IC: {ic})', linestyle='--')
        
        # Plot Phase Plane Trajectory
        ax_phase.plot(sol.y[0], sol.y[1], label=f'IC: {ic}', linewidth=2, linestyle='--', alpha=0.6)
        # Mark starting point
        ax_phase.scatter(ic[0], ic[1], color='red', zorder=5)

    # Mark the steady state
    ss_x, ss_y = A, B/A
    ax_phase.scatter(ss_x, ss_y, color='black', marker='*', s=150, label=f'Steady State ({ss_x}, {ss_y:.1f})', zorder=6)
    
    # Formatting
    ax_time.set_title(f'{config["name"]} - Time Course (A={A}, B={B})')
    ax_time.set_xlabel('Time')
    ax_time.set_ylabel('Concentration')
    ax_time.legend()
    ax_time.grid(True)
    
    ax_phase.set_title(f'{config["name"]} - Phase Plane (A={A}, B={B})')
    ax_phase.set_xlabel('x')
    ax_phase.set_ylabel('y')
    ax_phase.legend()
    ax_phase.grid(True)

plt.tight_layout()
plt.savefig("ass10/plot.png")
plt.show()